export const  SIGNUP_PROCESSING = "SIGNUP_PROCESSING"
export const  SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const  SIGNUP_FAIL = "SIGNUP_FAIL"

export const  LOGIN_PROCESSING = "LOGIN_PROCESSING"
export const  LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const  LOGIN_FAIL = "LOGIN_FAIL"

export const GET_LAUNCHES_DATA_PROCESSING = "GET_LAUNCHES_DATA_PROCESSING"
export const GET_LAUNCHES_DATA_SUCCESS = "GET_LAUNCHES_DATA_SUCCESS"
export const GET_LAUNCHES_DATA_FAIL = "GET_LAUNCHES_DATA_FAIL"

export const  LOGOUT_PROCESSING = "LOGOUT_PROCESSING"
export const  LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const  LOGOUT_FAIL = "LOGOUT_FAIL"